name: Node.js CI

on: [push, pull_request]
env:
  CI: true
  consumer_key: ${{secrets.consumer_key}}
  consumer_secret_key: ${{secrets.consumer_secret_key}}
  token: ${{secrets.token}}
  token_secret: ${{secrets.token_secret}}
  realm: ${{secrets.realm}}
  base_url: ${{secrets.base_url}}

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [18]
        os: [ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: yarn

      - name: Run tests
        run: yarn coverage
