name: Node.js CI

on:
  pull_request:

env:
  CI: true
  realm: ${{secrets.realm}}
  base_url: ${{secrets.base_url}}
  consumer_key: ${{secrets.consumer_key}}
  consumer_secret_key: ${{secrets.consumer_secret_key}}
  token: ${{secrets.token}}
  token_secret: ${{secrets.token_secret}}

jobs:
  test:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm coverage
